### ISSUE TITLE
Crash with Iguana Tweaks Reborn

### ISSUE THREAD

**Issue by CraftyZombie** [Da-Technomancer/Crossroads#278] opened 2024-02-24 04:26 UTC
**Describe the bug**
If Iguana Tweaks Reborn and Crossroads are both installed, the game crashes upon attempted world creation.

**To Reproduce [Optional]**
1. Install the following mods (1.20.1, Forge 47.2.20)

- crossroads-1.20.1-2.10.1
- essentials-1.20.1-2.16.0
- IguanaTweaksReborn-3.2.1-mc1.20.1
- InsaneLib-1.12.1-mc1.20.1
-  MaxHealthFix-Forge-1.20.1-12.0.2

2. Attempt to create a world.

**Expected behavior [Optional]**
The game shouldn't crash.

**Screenshots [Optional]**
N/A

**Additional context [Optional]**
Logs and crash report: https://gist.github.com/CraftyZombie/850b5a2a0156302a046babadf7078d31

**Comment by CraftyZombie** [comment] 2024-02-24 04:26
https://github.com/Insane96/IguanaTweaksReborn/issues/271

**Comment by Random-Scientist** [comment] 2024-02-24 07:39
I suspect this is being caused by liquid fat blobs
(edit, Techno beat me to it lol)

**Comment by Insane96** [comment] 2024-02-24 07:40
Will be fixed in the next ITR release

**Closed as completed** 2024-02-24 19:57 UTC
Labels: bug, Incompatability
