### ISSUE TITLE
missing tags

### ISSUE THREAD

**Issue by TheNimbleNinja** [Da-Technomancer/Crossroads#120] opened 2020-09-25 18:23 UTC
your missing tags from items in 1.16.2 and its refusing to create worlds cause of this

**Comment by Da-Technomancer** [comment] 2020-09-25 18:30
I need some actual information- world creation works fine under normal conditions.

Logs? Actual messages? How were you trying to make a world that failed? Which Crossroads version are you using? Where are you getting 'missing tags from items' from?

**Comment by Da-Technomancer** [comment] 2020-10-01 21:14
I'm closing this because there was so little information given, I can't even tell if they actually experienced a bug. I've also not reproduced any bug meeting this description.

**Closed as completed by Da-Technomancer** 2020-10-01 21:14 UTC
Labels: bug, Cannot Reproduce, Invalid
